language: php

php:
  - 7.1.11

services:
  - mysql

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS myapp_test;'

before_script:

test:
  adapter: mysql2
  database: myapp_test
  username: travis
  encoding: utf8

script: phpunit

dist: precise